(()=>{'use strict';
const cv=document.querySelector('#game'),ctx=cv.getContext('2d');const TOTAL=40,GAPS=[{n:'КОРОТКИЙ',v:105},{n:'СРЕДНИЙ',v:175},{n:'ДАЛЬНИЙ',v:250}];let W,H,dpr,plats,player,idx,state,falls,time,last,cam,seed,rng;const keys={};let touch={left:false,right:false,jump:false};
const $=id=>document.getElementById(id);const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const pad=n=>String(n).padStart(2,'0');const fmt=t=>{let m=Math.floor(t/60),s=t-m*60;return `${m}:${pad(Math.floor(s))}.${Math.floor(s%1*10)}`};
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;cv.width=W*dpr;cv.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function random(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}function pick(a){return a[Math.floor(random()*a.length)]}
function build(){plats=[{x:80,y:420,w:210,h:20,i:0,gap:0}];for(let i=1;i<TOTAL;i++){let p=plats[i-1],g=pick(GAPS),y=clamp(p.y+pick([-70,-32,0,27,55]),230,440);plats.push({x:p.x+p.w+g.v,y,w:125+random()*85,h:20,i,gap:GAPS.indexOf(g)})}}
function reset(){seed=(Math.random()*0xffffffff)>>>0;build();idx=0;falls=0;time=0;cam=0;player={x:plats[0].x+75,y:plats[0].y-38,w:32,h:38,vx:0,vy:0,ground:true,rot:0};state='play';hide();$('hud').classList.add('on');updateHud()}
function hide(){document.querySelectorAll('.overlay').forEach(x=>x.classList.remove('show'))}function show(id){$(id).classList.add('show')}
function updateHud(){$('current').textContent=pad(idx+1);$('fill').style.width=((idx+1)/TOTAL*100)+'%';$('falls').textContent=`${falls} / 5`;let next=plats[idx+1];$('gap').textContent=next?GAPS[next.gap].n:'ФИНИШ'}
function visible(p){return p.i>=Math.max(0,idx-2)&&p.i<=Math.min(TOTAL-1,idx+2)}
function update(dt){if(state!=='play')return;let l=keys.ArrowLeft||keys.KeyA||touch.left,r=keys.ArrowRight||keys.KeyD||touch.right,j=keys.Space||keys.ArrowUp||keys.KeyW||touch.jump;if(l)player.vx-=.7*dt;if(r)player.vx+=.7*dt;if(!l&&!r)player.vx*=Math.pow(.78,dt);player.vx=clamp(player.vx,-7,7);if(j&&player.ground){player.vy=-13;player.ground=false}let old=player.y+player.h;player.vy=clamp(player.vy+.65*dt,-20,16);player.x+=player.vx*dt;player.y+=player.vy*dt;player.ground=false;for(let p of plats){if(!visible(p)||player.vy<0)continue;if(old<=p.y+4&&player.y+player.h>=p.y&&player.x+player.w>p.x+8&&player.x<p.x+p.w-8){player.y=p.y-player.h;player.vy=0;player.ground=true;if(p.i>idx){idx=p.i;updateHud();if(idx===TOTAL-1)win()}}}if(player.y>H+200)die();let target=player.x-W*.4;cam+=(target-cam)*.1;cam=Math.max(0,Math.min(cam,plats[TOTAL-1].x-W+180));$('time').textContent=fmt(time)}
function die(){falls++;updateHud();if(falls>=5){state='over';show('over');return}let p=plats[idx];player.x=p.x+45;player.y=p.y-player.h;player.vx=0;player.vy=0}
function win(){state='win';$('winStats').textContent=`Время ${fmt(time)} · падений ${falls} · seed ${seed.toString(36).toUpperCase()}`;show('win')}
function drawBg(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#071424');g.addColorStop(.6,'#12384a');g.addColorStop(1,'#1e5557');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#ffe1a0';ctx.globalAlpha=.7;ctx.beginPath();ctx.arc(W*.74,H*.25,42,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;for(let i=0;i<45;i++){ctx.fillStyle='#fff4d633';ctx.fillRect((i*193-cam*.15)%W,(i*79)%H*.55,2,2)}ctx.fillStyle='#081b29';ctx.beginPath();ctx.moveTo(0,H);for(let x=0;x<=W;x+=30)ctx.lineTo(x,H*.62+Math.sin((x+cam*.15)*.012)*30);ctx.lineTo(W,H);ctx.fill()}
function platform(p){if(!visible(p))return;let x=p.x-cam;if(x+p.w<0||x>W)return;ctx.fillStyle='#102536';ctx.fillRect(x,p.y,p.w,p.h);ctx.fillStyle='#f1bb5a';ctx.fillRect(x,p.y,p.w,5);ctx.fillStyle='#6ba784';for(let k=10;k<p.w;k+=32){ctx.fillRect(x+k,p.y-5,2,5);ctx.fillRect(x+k+2,p.y-8,2,8)}}
function pent(x,y,r,a){ctx.beginPath();for(let i=0;i<5;i++){let t=a-Math.PI/2+i*Math.PI*2/5;let X=x+Math.cos(t)*r,Y=y+Math.sin(t)*r;i?ctx.lineTo(X,Y):ctx.moveTo(X,Y)}ctx.closePath()}
function draw(){drawBg();plats.forEach(platform);let x=player.x-cam+player.w/2,y=player.y+player.h/2;ctx.save();ctx.translate(x,y);ctx.rotate(player.rot);pent(0,0,24,0);ctx.fillStyle='#ffd23f';ctx.fill();ctx.strokeStyle='#765400';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-7,-4,5,0,7);ctx.arc(7,-4,5,0,7);ctx.fill();ctx.fillStyle='#201a05';ctx.beginPath();ctx.arc(-6,-4,2,0,7);ctx.arc(8,-4,2,0,7);ctx.fill();ctx.restore()}
function frame(now){let dt=Math.min((now-last)/16.67,2);last=now;if(state==='play'){time+=dt/60;update(dt)}draw();requestAnimationFrame(frame)}
addEventListener('keydown',e=>{keys[e.code]=true;if(['ArrowLeft','ArrowRight','ArrowUp','Space'].includes(e.code))e.preventDefault();if(e.code==='KeyR')reset();if(e.code==='KeyP'&&state==='play'){state='pause';show('pause')}else if(e.code==='KeyP'&&state==='pause'){state='play';hide();$('hud').classList.add('on')}});addEventListener('keyup',e=>keys[e.code]=false);
document.querySelectorAll('#touch button').forEach(b=>{let k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();touch[k]=true});['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>touch[k]=false))});$('start').onclick=reset;$('resume').onclick=()=>{state='play';hide();$('hud').classList.add('on')};$('again').onclick=reset;$('retry').onclick=reset;
state='menu';seed=1;build();idx=0;player={x:150,y:380,w:32,h:38,vx:0,vy:0,ground:true,rot:0};last=performance.now();requestAnimationFrame(frame);
})();
